version: "3"

services:
  study2024:
    container_name: study2024
    image: study2024
    ports:
      - 8000:8080
    volumes:
      - ./data/settings/settings2.json:/data/settings/settings2.json
      - ./data/logs/logs.dat:/data/logs/logs.dat
networks:
  default: